apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service-vault
  annotations:
    vault.io/secrets-path: test/vidhya_elango
    vault.io/secrets-engine: secrets
spec:
  type: service
  owner: my-vault-team
  lifecycle: production
