apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service-vault
  annotations:
    vault.io/secrets-path: secrets/data/test/backstage
    vault.io/secrets-engine: secrets
spec:
  type: service
  owner: my-vault-team
  lifecycle: production
